// ============================================================
// 千葉大ナビ 団体データ(叩き台版)
// ・団体名は公開情報(2024-2026年の新歓サイト等)に基づく実在団体
// ・会費/頻度/飲み会/4軸タグなどは【すべて運営の推定値】です
// ・verified:false = 未確認。ヒアリング回答が来たら上書きして true に
// ・insta が空("")の団体はGoogle検索リンクにフォールバックします
//
// 1行の書式:
// G(名前, 活動内容, ジャンル, 区分, キャンパス, 4軸, 週日数, 半期会費, その他費用, オプション)
//   区分: "club"=部活(公認) "circle_k"=公認サークル "circle_h"=非公認 "gakusei"=学生団体
//   キャンパス: "nishichiba" | "inohana" | "matsudo"
//   4軸: 4文字 例"AGWS" (A/C, G/E, W/F, S/H)
//   オプション(省略可): {insta:"URL", drink:0-2, beginner:true/false,
//     midEntry:true/false, incare:true/false, size:人数, eventLove:t/f,
//     genderMix:t/f, verified:t/f}
// ============================================================

let _id = 0;
function G(name, activity, genre, kubun, campus, tags, days, feeHalf, feeOther, opts = {}) {
  _id++;
  return Object.assign({
    id: "g" + String(_id).padStart(3, "0"),
    name, activity, genre, kubun, campus,
    axes: { a: tags[0], g: tags[1], w: tags[2], s: tags[3] },
    days, feeHalf, feeOther,
    incare: false, drink: 1, eventLove: true, beginner: true,
    genderMix: true, midEntry: true, size: 30, insta: "", verified: false
  }, opts);
}

const GROUPS = [
  {
    id: "g001",
    name: "硬式野球部",
    activity: "硬式野球",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 5,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: false,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g002",
    name: "準硬式野球部",
    activity: "準硬式野球",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 4,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g003",
    name: "男子サッカー部",
    activity: "サッカー",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 4,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: false,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g004",
    name: "女子サッカー部",
    activity: "サッカー",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g005",
    name: "ラグビー部",
    activity: "ラグビー",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 4,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g006",
    name: "アメリカンフットボール部",
    activity: "アメフト",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 4,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g007",
    name: "硬式庭球部",
    activity: "硬式テニス",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 4,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: false,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g008",
    name: "ソフトテニス部",
    activity: "ソフトテニス",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: false,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g009",
    name: "男子バスケットボール部",
    activity: "バスケットボール",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 4,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: false,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g010",
    name: "女子バスケットボール部",
    activity: "バスケットボール",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: false,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g011",
    name: "男子バレーボール部",
    activity: "バレーボール",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: false,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g012",
    name: "女子バレーボール部",
    activity: "バレーボール",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: false,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g013",
    name: "バドミントン部",
    activity: "バドミントン",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: false,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g014",
    name: "卓球部",
    activity: "卓球",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: false,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g015",
    name: "ハンドボール部",
    activity: "ハンドボール",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g016",
    name: "男子ラクロス部",
    activity: "ラクロス",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 4,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g017",
    name: "女子ラクロス部",
    activity: "ラクロス",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 4,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g018",
    name: "男子ソフトボール部",
    activity: "ソフトボール",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g019",
    name: "女子ソフトボール部",
    activity: "ソフトボール",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g020",
    name: "フットサル部",
    activity: "フットサル",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: false,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g021",
    name: "セパタクロー部",
    activity: "セパタクロー",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g022",
    name: "ゴルフ部",
    activity: "ゴルフ",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g023",
    name: "柔道部",
    activity: "柔道",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g024",
    name: "剣道部",
    activity: "剣道",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: false,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g025",
    name: "弓道部",
    activity: "弓道",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g026",
    name: "空手部",
    activity: "空手",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g027",
    name: "合気道部",
    activity: "合気道",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g028",
    name: "少林寺拳法部",
    activity: "少林寺拳法",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g029",
    name: "躰道部",
    activity: "躰道",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g030",
    name: "陸上競技部",
    activity: "陸上競技",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 5,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: false,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g031",
    name: "水泳部",
    activity: "競泳",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 4,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: false,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g032",
    name: "漕艇部",
    activity: "ボート(創部100年)",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g033",
    name: "ヨット部",
    activity: "ヨット",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g034",
    name: "体操競技部",
    activity: "体操競技",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: false,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g035",
    name: "競技ダンス部",
    activity: "競技ダンス",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g036",
    name: "モダンダンス部",
    activity: "モダンダンス",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g037",
    name: "民族舞踊部",
    activity: "民族舞踊",
    genre: "文化系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g038",
    name: "ワンダーフォーゲル部",
    activity: "登山・アウトドア",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g039",
    name: "オリエンテーリング部",
    activity: "オリエンテーリング",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g040",
    name: "トライアスロン部",
    activity: "トライアスロン",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 4,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g041",
    name: "スキー部",
    activity: "スキー",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g042",
    name: "スケート部",
    activity: "スケート・アイスホッケー",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g043",
    name: "馬術部",
    activity: "馬術",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 4,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g044",
    name: "ライフル射撃部",
    activity: "ライフル射撃",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g045",
    name: "ボルダリング部",
    activity: "ボルダリング",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g046",
    name: "サッカー同好会",
    activity: "サッカー",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g047",
    name: "FC RIFLIE",
    activity: "サッカー",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g048",
    name: "CATS",
    activity: "硬式テニス",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g049",
    name: "硬式庭球サークル あまりぃず",
    activity: "硬式テニス",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g050",
    name: "MAYBE GOOD",
    activity: "硬式テニス",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g051",
    name: "POTATO",
    activity: "硬式テニス",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g052",
    name: "ソフトテニスサークル YELL",
    activity: "ソフトテニス",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g053",
    name: "H.C.K",
    activity: "バスケットボール",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g054",
    name: "燃焼系",
    activity: "バレーボール",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g055",
    name: "骨折り損のバレーボール同好会",
    activity: "バレーボール",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g056",
    name: "おれんじes",
    activity: "バドミントン",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g057",
    name: "B.A.S.S.",
    activity: "バドミントン",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g058",
    name: "VERDE",
    activity: "バドミントン",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g059",
    name: "アルティメット同好会",
    activity: "アルティメット",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g060",
    name: "Lips",
    activity: "チアリーディング",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g061",
    name: "ストリートダンスサークルDLC",
    activity: "ストリートダンス",
    genre: "運動系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g062",
    name: "コピーダンスサークル Drop",
    activity: "コピーダンス",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g063",
    name: "ダブルダッチサークルAX",
    activity: "ダブルダッチ",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g064",
    name: "OUTKROG",
    activity: "スキューバダイビング",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g065",
    name: "サイクリング部",
    activity: "サイクリング",
    genre: "運動系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g066",
    name: "キャンピングツアー部",
    activity: "キャンプ・旅行",
    genre: "運動系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g067",
    name: "WOOD STOCK",
    activity: "スノーボード・スキー",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g068",
    name: "自動車部",
    activity: "自動車・ドライブ",
    genre: "運動系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g069",
    name: "剣道サークル 志剣",
    activity: "剣道",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g070",
    name: "ジークンドークラブ",
    activity: "ジークンドー",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g071",
    name: "医学部硬式野球部",
    activity: "硬式野球",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "inohana",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g072",
    name: "医学部サッカー部",
    activity: "サッカー",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "inohana",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g073",
    name: "医学部ラグビー部",
    activity: "ラグビー",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "inohana",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "H"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g074",
    name: "医薬看硬式庭球部",
    activity: "硬式テニス",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "inohana",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g075",
    name: "医薬軟式庭球部",
    activity: "ソフトテニス",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "inohana",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g076",
    name: "亥鼻男子バスケットボール部",
    activity: "バスケットボール",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "inohana",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g077",
    name: "医薬看女子バスケットボール部",
    activity: "バスケットボール",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "inohana",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g078",
    name: "医薬看男子バレーボール部",
    activity: "バレーボール",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "inohana",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g079",
    name: "医薬看女子バレーボール部",
    activity: "バレーボール",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "inohana",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g080",
    name: "亥鼻バドミントン部",
    activity: "バドミントン",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "inohana",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g081",
    name: "亥鼻卓球部",
    activity: "卓球",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "inohana",
    axes: {
      a: "A",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g082",
    name: "亥鼻フットサル部",
    activity: "フットサル",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "inohana",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g083",
    name: "医薬看護学部剣道部",
    activity: "剣道",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "inohana",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g084",
    name: "医学部弓道部",
    activity: "弓道",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "inohana",
    axes: {
      a: "C",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g085",
    name: "亥鼻空手道部",
    activity: "空手",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "inohana",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g086",
    name: "亥鼻陸上競技部",
    activity: "陸上競技",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "inohana",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g087",
    name: "医学部水泳部",
    activity: "水泳",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "inohana",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g088",
    name: "医学部スキー部",
    activity: "スキー",
    genre: "運動系",
    kubun: "club",
    incare: false,
    campus: "inohana",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: false,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g089",
    name: "IDC(亥鼻ダンスサークル)",
    activity: "ダンス",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "inohana",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g090",
    name: "亥鼻マッスルサークル",
    activity: "筋トレ",
    genre: "運動系",
    kubun: "circle_h",
    incare: false,
    campus: "inohana",
    axes: {
      a: "A",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g091",
    name: "管弦楽団",
    activity: "オーケストラ",
    genre: "音楽系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: false,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g092",
    name: "吹奏楽団",
    activity: "吹奏楽",
    genre: "音楽系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: false,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g093",
    name: "合唱団",
    activity: "合唱",
    genre: "音楽系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "G",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g094",
    name: "ウボイコール",
    activity: "男声合唱",
    genre: "音楽系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "G",
      w: "F",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g095",
    name: "アカペラサークル T.o.N.E.",
    activity: "アカペラ",
    genre: "音楽系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g096",
    name: "軽音楽部",
    activity: "バンド活動",
    genre: "音楽系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g097",
    name: "モダンジャズ研究会",
    activity: "ジャズ演奏",
    genre: "音楽系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g098",
    name: "マンドリンクラブ",
    activity: "マンドリン合奏",
    genre: "音楽系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "G",
      w: "F",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g099",
    name: "ギタークラブ",
    activity: "クラシックギター",
    genre: "音楽系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "G",
      w: "F",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g100",
    name: "アコギサークル アンプラグド",
    activity: "アコースティックギター",
    genre: "音楽系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g101",
    name: "サウンドハウスZOO",
    activity: "軽音・バンド",
    genre: "音楽系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g102",
    name: "エレクトーンサークル えれちば",
    activity: "エレクトーン",
    genre: "音楽系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g103",
    name: "ショパンの会",
    activity: "ピアノ",
    genre: "音楽系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g104",
    name: "コンフローレ室内合奏団",
    activity: "室内楽",
    genre: "音楽系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g105",
    name: "リコーダーアンサンブル",
    activity: "リコーダー合奏",
    genre: "音楽系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g106",
    name: "カントリー&ウエスタン研究会",
    activity: "カントリー音楽",
    genre: "音楽系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g107",
    name: "紫千会",
    activity: "邦楽・和楽器",
    genre: "音楽系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "G",
      w: "F",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g108",
    name: "ゐのはな音楽部",
    activity: "オーケストラ",
    genre: "音楽系",
    kubun: "circle_h",
    incare: false,
    campus: "inohana",
    axes: {
      a: "C",
      g: "G",
      w: "W",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g109",
    name: "亥鼻バンドサークル",
    activity: "バンド活動",
    genre: "音楽系",
    kubun: "circle_h",
    incare: false,
    campus: "inohana",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g110",
    name: "亥鼻ジャズ研究会",
    activity: "ジャズ演奏",
    genre: "音楽系",
    kubun: "circle_h",
    incare: false,
    campus: "inohana",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g111",
    name: "亥鼻ぴあの倶楽部",
    activity: "ピアノ",
    genre: "音楽系",
    kubun: "circle_h",
    incare: false,
    campus: "inohana",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g112",
    name: "演劇部",
    activity: "演劇",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g113",
    name: "劇団個人主義",
    activity: "演劇",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g114",
    name: "劇団NONNY",
    activity: "演劇",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g115",
    name: "お笑いサークルP-RITTS",
    activity: "お笑い・ネタ",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g116",
    name: "落語研究会",
    activity: "落語",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g117",
    name: "美術サークル",
    activity: "絵画・創作",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g118",
    name: "写真部",
    activity: "写真撮影・展示",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g119",
    name: "カラー写真をつくる会",
    activity: "写真・現像",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g120",
    name: "茶道部",
    activity: "茶道",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "G",
      w: "F",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g121",
    name: "書道サークルぼくじる九思会",
    activity: "書道",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g122",
    name: "将棋部",
    activity: "将棋",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g123",
    name: "囲碁部",
    activity: "囲碁",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g124",
    name: "チェス研究会",
    activity: "チェス",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g125",
    name: "競技かるた会",
    activity: "競技かるた",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g126",
    name: "漫画研究会",
    activity: "漫画・イラスト",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g127",
    name: "アニメーション研究会",
    activity: "アニメ・創作",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g128",
    name: "シネマウント・フィルム・パーティー",
    activity: "映画制作・鑑賞",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g129",
    name: "文藝部",
    activity: "小説・文芸創作",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g130",
    name: "推理小説同好会",
    activity: "ミステリ読書",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g131",
    name: "鉄道研究会",
    activity: "鉄道",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g132",
    name: "C.D.C.",
    activity: "ディズニー",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g133",
    name: "ちばポケ",
    activity: "ポケモン",
    genre: "文化系",
    kubun: "circle_h",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g134",
    name: "サバイバルゲーム研究会",
    activity: "サバゲー",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g135",
    name: "マジックサークルCMC",
    activity: "マジック",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g136",
    name: "ジャグリングチーム Possum",
    activity: "ジャグリング",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g137",
    name: "クイズ研究会 ミルフィーユ",
    activity: "クイズ",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g138",
    name: "鳥人間サークル T-MIT",
    activity: "人力飛行機の設計・製作",
    genre: "技術系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g139",
    name: "フォーミュラプロジェクト(CUFP)",
    activity: "学生フォーミュラ・車両製作",
    genre: "技術系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 3,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g140",
    name: "Chiba Robot Studio",
    activity: "ロボット製作",
    genre: "技術系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g141",
    name: "電子計算機研究会",
    activity: "プログラミング・PC",
    genre: "技術系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "S"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g142",
    name: "星を見る会",
    activity: "天体観測",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g143",
    name: "植物同好会",
    activity: "植物観察",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g144",
    name: "釣部",
    activity: "釣り",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g145",
    name: "放送研究会",
    activity: "放送・映像・アナウンス",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "S"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g146",
    name: "仏教哲学研究会",
    activity: "哲学・思想",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g147",
    name: "縫製技術研究会",
    activity: "裁縫・服作り",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g148",
    name: "Fabric",
    activity: "服飾・ファッション",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "S"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g149",
    name: "地域猫の会 ちばねこ",
    activity: "地域猫の保護活動",
    genre: "学生団体",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g150",
    name: "手話サークル ウルトラマンの会",
    activity: "手話",
    genre: "学生団体",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g151",
    name: "東洋医学研究会",
    activity: "東洋医学の勉強会",
    genre: "文化系",
    kubun: "circle_h",
    incare: false,
    campus: "inohana",
    axes: {
      a: "C",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g152",
    name: "世界の医療を考える会",
    activity: "国際医療の勉強会",
    genre: "学生団体",
    kubun: "circle_h",
    incare: false,
    campus: "inohana",
    axes: {
      a: "C",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g153",
    name: "C-TAT",
    activity: "医療系活動",
    genre: "学生団体",
    kubun: "circle_h",
    incare: false,
    campus: "inohana",
    axes: {
      a: "C",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g154",
    name: "Public Health 実践講座",
    activity: "公衆衛生の実践学習",
    genre: "学生団体",
    kubun: "circle_h",
    incare: false,
    campus: "inohana",
    axes: {
      a: "C",
      g: "G",
      w: "F",
      s: "S"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g155",
    name: "千葉大祭実行委員会",
    activity: "大学祭の企画運営",
    genre: "学生団体",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 2,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g156",
    name: "環境ISO学生委員会",
    activity: "環境活動・ISO運用",
    genre: "学生団体",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "G",
      w: "W",
      s: "S"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g157",
    name: "生協学生委員会(C.G.I.)",
    activity: "生協の学生活動",
    genre: "学生団体",
    kubun: "gakusei",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g158",
    name: "地域子ども研究会 あらぐさ",
    activity: "子ども支援",
    genre: "学生団体",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g159",
    name: "人形劇サークル かざぐるま",
    activity: "人形劇",
    genre: "文化系",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g160",
    name: "のびのびの樹",
    activity: "子ども支援ボランティア",
    genre: "学生団体",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g161",
    name: "障害者問題研究会 おにっこ",
    activity: "障がい者支援・交流",
    genre: "学生団体",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g162",
    name: "千葉ぬいぐるみ病院",
    activity: "ぬいぐるみ病院活動",
    genre: "学生団体",
    kubun: "circle_h",
    incare: false,
    campus: "inohana",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g163",
    name: "亥鼻手話の会",
    activity: "手話",
    genre: "学生団体",
    kubun: "circle_h",
    incare: false,
    campus: "inohana",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g164",
    name: "亥鼻祭実行委員会",
    activity: "亥鼻祭の企画運営",
    genre: "学生団体",
    kubun: "circle_h",
    incare: false,
    campus: "inohana",
    axes: {
      a: "A",
      g: "E",
      w: "W",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  },
  {
    id: "g165",
    name: "Music Society 道しるべ",
    activity: "音楽ボランティア",
    genre: "学生団体",
    kubun: "circle_k",
    incare: false,
    campus: "nishichiba",
    axes: {
      a: "C",
      g: "E",
      w: "F",
      s: "H"
    },
    days: 1,
    feeHalf: null,
    feeOther: null,
    drink: 1,
    eventLove: true,
    beginner: true,
    genderMix: true,
    midEntry: true,
    size: null,
    insta: null,
    verified: false
  }
];

// ======================================================
// 16タイプ定義
// ======================================================
const TYPES = {
  AGWS: { name: "体育会エース", copy: "本気の勝負と仲間の熱量、どちらも欲しい実力派。", desc: "大人数の中で結果を追いかけるのが一番燃えるタイプ。部活や大会志向の大型サークルで輝きます。" },
  AGWH: { name: "熱血ムードメーカー", copy: "ガチで打ち込みつつ、チームの空気も大事にする。", desc: "本気の活動の中に居場所を求めるタイプ。全力で頑張る仲間と一緒にいることがエネルギー源です。" },
  AGFS: { name: "求道者アスリート", copy: "少数精鋭でストイックに上を目指す。", desc: "群れるより、本気の少人数で技を磨きたいタイプ。専門性の高い部活・競技系が向いています。" },
  AGFH: { name: "少数精鋭プレイヤー", copy: "信頼できる仲間と、本気の時間を積み重ねる。", desc: "気の合う数人と深く打ち込むのが理想。小規模でも活動が濃い団体と相性抜群です。" },
  AEWS: { name: "イベントリーダー", copy: "動いて、企画して、経験を実績に変える。", desc: "アクティブに楽しみながら、将来につながる経験も欲しいタイプ。イベント系・企画系の大型団体向き。" },
  AEWH: { name: "祭りの中心", copy: "大人数でワイワイ、楽しさこそ正義。", desc: "みんなで盛り上がる時間が何より好き。エンジョイ系の大型スポーツサークルやイベントサークルが天職です。" },
  AEFS: { name: "アクティブ職人", copy: "体を動かしつつ、自分のスキルも磨きたい。", desc: "楽しく活動しながら、着実に上達したいタイプ。少人数で丁寧に教え合える団体が合います。" },
  AEFH: { name: "仲良しスポーツ派", copy: "気の合う仲間と、ゆるく楽しく体を動かす。", desc: "勝ち負けより一緒に過ごす時間が大事。小規模でアットホームな運動系サークルがぴったり。" },
  CGWS: { name: "プロデューサー", copy: "大きな舞台を、本気で作り上げる側の人。", desc: "文化系の活動を大人数で本気でやりたいタイプ。演奏会・公演・大規模企画のある団体で力を発揮します。" },
  CGWH: { name: "文化祭の主役", copy: "本気の作品づくりと、にぎやかな仲間たち。", desc: "打ち込める文化系活動と、大勢の居心地いい仲間の両方を求めるタイプ。大型の音楽・パフォーマンス系向き。" },
  CGFS: { name: "静かな職人", copy: "少人数で、じっくり深く極める。", desc: "騒がしさより集中できる環境が好き。専門性のある文化系・研究系の団体で真価を発揮します。" },
  CGFH: { name: "こだわり仲間派", copy: "好きなことを、好きな人たちと深く。", desc: "共通の趣味で深くつながれる少人数の団体が理想。伝統文化系や創作系と好相性です。" },
  CEWS: { name: "器用な社交家", copy: "楽しみながら、人脈も経験も広げていく。", desc: "ゆるく楽しみつつ将来にも目を向けるバランス型。交流系・イベント系の団体が合います。" },
  CEWH: { name: "サロンの住人", copy: "にぎやかな場所で、のんびり自分らしく。", desc: "大人数の中でまったり過ごすのが心地いいタイプ。ゆるめの大型文化系サークルがおすすめ。" },
  CEFS: { name: "マイペース研究家", copy: "自分のペースで、興味をとことん掘る。", desc: "少人数で気楽に、でも中身のある活動がしたいタイプ。趣味系・学術系の小規模団体向き。" },
  CEFH: { name: "縁側ゆったり", copy: "居心地のよさが、いちばんのごちそう。", desc: "ホッとできる居場所を求めるタイプ。ゆるくて温かい小規模サークルがぴったりです。" }
};

// 診断の質問(7段階: 左=そう思う +3 〜 右=そう思わない -3)
const QUESTIONS = [
  { text: "体を動かすのが好き", axis: "a", rev: false },
  { text: "インドアな趣味の方が合う", axis: "a", rev: true },
  { text: "大会や発表で結果を出したい", axis: "g", rev: false },
  { text: "楽しさ重視でゆるくやりたい", axis: "g", rev: true },
  { text: "大人数でワイワイしたい", axis: "w", rev: false },
  { text: "少人数で深く付き合いたい", axis: "w", rev: true },
  { text: "就活や将来に活きる経験がしたい", axis: "s", rev: false },
  { text: "居心地のいい居場所がほしい", axis: "s", rev: true },
  { text: "飲み会は多くてもいい", axis: "drink", rev: false },
  { text: "合宿や学祭には積極的に参加したい", axis: "event", rev: false },
  { text: "経験のあることを続けたい", axis: "exp", rev: false },
  { text: "男女比は気にしない", axis: "gender", rev: false }
];
